version: "3"

services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: db
    image: mongo
    ports:
      - 27017:27017
